### ISSUE TITLE
armory offline 

### ISSUE THREAD

**Issue by FredericHeem** [olalonde/proof-of-assets#2]
Dear,
Is there any chance that baproof be compatible with armory in offline mode ?
Best Regards,

**Comment by olalonde** [comment]
Sure, I will try to :)

**Comment by FredericHeem** [comment]
Have a look at the asset_proof.py script in the pull request https://github.com/etotheipi/BitcoinArmory/pull/184/files
It creates the asset file in json format equal to the baproof signall command.

**Comment by olalonde** [comment]
Thanks! Linked to your implementation in README.
