### ISSUE TITLE
btc-assets.json should include the last blockheight.

### ISSUE THREAD

**Issue by jaekwon** [olalonde/proof-of-assets#7]
and btc-root.json should include the last blockheight & global timestamp as well.

When a user verifies the btc-assets, the user should only count the address balance up until the specified blockheight. Otherwise new outgoing (withdrawal/sweep) transactions can mess up the verification process.

**Comment by olalonde** [comment]
Agreed.

**Comment by olalonde** [comment]
In fact, this meta data should probably be part of the liability proof. The same assets proof could be used by different liability proofs but when verifying the amount for a given liability proof, the verifier should check the total assets at the moment the liability proof was created.

**Comment by janx** [comment]
timestamp +1
